
interfaces:
  spine1:
    loopback: "10.2.1.1"
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1", "bond2", "bond3"]
    peerlink:
      - name: "peerlink"
        members: ["swp7", "swp8"]
        clag_ip: "169.254.254.1"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"
    bond2:
      - name: "bond2"
        members: ["swp3", "swp4"]
        clag_id: "2"
    bond3:
      - name: "bond3"
        members: ["swp5", "swp6"]
        clag_id: "3"
  spine2:
    loopback: "10.2.1.2"
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1", "bond2", "bond3"]
    peerlink:
      - name: "peerlink"
        members: ["swp7", "swp8"]
        clag_ip: "169.254.254.2"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"
    bond2:
      - name: "bond2"
        members: ["swp3", "swp4"]
        clag_id: "2"
    bond3:
      - name: "bond3"
        members: ["swp5", "swp6"]
        clag_id: "3"
  leaf1:
    loopback: "10.2.1.3"
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.1"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"
  leaf2:
    loopback: "10.2.1.4"
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.2"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"
  leaf3:
    loopback: "10.2.1.5"
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.1"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"
  leaf4:
    loopback: "10.2.1.6"
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.2"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"
  leaf5:
    loopback: "10.2.1.7"
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.1"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"
  leaf6:
    loopback: "10.2.1.8"
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1"]
    peerlink:
      - name: "peerlink"
        members: ["swp3", "swp4"]
        clag_ip: "169.254.254.2"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"


addresses:
  spine1:
    clag_ip: "169.254.254.1/30"
    clag_peer: "169.254.254.2"
    clag_mac: "44:38:39:ff:00:01"
    svi: "10.1.10.252/24"
  spine2:
    clag_ip: "169.254.254.2/30"
    clag_peer: "169.254.254.1"
    clag_mac: "44:38:39:ff:00:01"
    svi: "10.1.10.253/24"
  leaf1:
    clag_ip: "169.254.254.1/30"
    clag_peer: "169.254.254.2"
    clag_mac: "44:38:39:ff:00:02"
    svi: "10.1.10.1/24"
  leaf2:
    clag_ip: "169.254.254.2/30"
    clag_peer: "169.254.254.1"
    clag_mac: "44:38:39:ff:00:02"
    svi: "10.1.10.2/24"
  leaf3:
    clag_ip: "169.254.254.1/30"
    clag_peer: "169.254.254.2"
    clag_mac: "44:38:39:ff:00:03"
    svi: "10.1.10.3/24"
  leaf4:
    clag_ip: "169.254.254.2/30"
    clag_peer: "169.254.254.1"
    clag_mac: "44:38:39:ff:00:03"
    svi: "10.1.10.4/24"
  leaf5:
    clag_ip: "169.254.254.1/30"
    clag_peer: "169.254.254.2"
    clag_mac: "44:38:39:ff:00:04"
    svi: "10.1.10.5/24"
  leaf6:
    clag_ip: "169.254.254.2/30"
    clag_peer: "169.254.254.1"
    clag_mac: "44:38:39:ff:00:04"
    svi: "10.1.10.6/24"


vrr:
  spine1:
    vip: "10.1.10.254/24"
    vmac: "00:11:22:33:44:55"
  spine2:
    vip: "10.1.10.254/24"
    vmac: "00:11:22:33:44:55"





